---
- hosts: workstation
  become: true 
  gather_facts: yes

  tasks:

    - name: Debug OS distribution
      debug:
        msg: "The OS distribution is {{ ansible_distribution }}."


    - name: Include Fedora Setup tasks if OS is Fedora
      include_tasks: Fedora-workstation/fedora.yml
      when: ansible_distribution == "Fedora"