---
- hosts: workstation
  become: true 
  gather_facts: yes

  tasks:
    - name: Include Fedora Setup tasks if OS is Fedora
      iclude_tasks: Fedora-workstation/FedoraSetup.yml
      when: ansible_distribution == "Fedora"