---
- name: Check and setup Fedora workstation
  hosts: workstation
  become: true 
  gather_facts: yes

  tasks:
    - name: Check if Fedora workstation
      fail:
        msg: "This is not a Fedora workstation"
      when: ansible_distribution != 'Fedora'
      - include_tasks: /Fedora-workstation/FedoraSetup.yml


