---
- name: Check and setup Fedora workstation
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Include tasks if OS is Fedora
        include_tasks: Fedora-workstation/FedoraSetup.yml
        when: ansible_distribution == 'Fedora'
