---
- name: Check and setup Fedora workstation
  hosts: workstation
  become: true 
  gather_facts: yes

tasks:
  - include_tasks: Fedora-workstation/FedoraSetup.yml
    when: ansible_distribution == 'Fedora'

