---
- name: Check and setup Fedora workstation
  hosts: workstation
  become: true 
  gather_facts: yes

  tasks:
    - name: Specific task for Fedora

  - include_tasks: /Fedora-workstation/FedoraSetup.yml
     when: ansible_distribution == "Fedora"
