---
- name: Check and setup Fedora workstation
  hosts: workstation
  become: true 
  gather_facts: yes

  tasks:
    - name: Specific task for Fedora
      debug:
        msg: "Running a Fedora-specific task."
      when: ansible_distribution == "Fedora"
