---
- name: Copy wallpaper file with debug
  block:
    - name: Debug start message
      debug:
        msg: "Starting to copy wallpaper file"
    - name: Print current file path
      debug:
        msg: "Current playbook path is: {{ playbook_dir }}"

    - name: Copy wallpaper file
      copy:
        src: Fedora-workstation/Templates/wallpaper.png
        dest: "./home/taco/.wallpaper.png"
     # ignore_errors: true

    - name: Debug end message
      debug:
        msg: "Finished copying wallpaper file"

- name: Set GNOME wallpaper with debug
  become: true
  become_method: sudo
  block:
    - name: Debug start message
      debug:
        msg: "Starting to set GNOME wallpaper"
    
  #  - name: Ensure psutil is installed
   ##    name: psutil
#        state: present

    - name: Set GNOME wallpaper
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "./home/taco/.wallpaper.png" 

    - name: Debug end message
      debug:
        msg: "Finished setting GNOME wallpaper"

- name: Set GNOME Wallpaper scale with debug
  become_method: sudo
  block:
    - name: Debug start message
      debug:
        msg: "Starting to set GNOME wallpaper scale"

    - name: Set GNOME Wallpaper scale
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'scaled'"
      ignore_errors: true

    - name: Debug end message
      debug:
        msg: "Finished setting GNOME wallpaper scale"
