--- 
- name: Package debug 
  debug:
    msg: "Updgrading all packages"
- name: Upgrade all packages
  dnf: 
    name: "*"
    state: latest

#- name: Install group packages whenever I make groups :)
## dnf: 
#    name:
#       - "@TacoBell"
#    state: installed



- name: Display the value of ansible_distribution
  debug:
    msg: "Installing all packages"

- name: Install packages
  become: true
  dnf:
    name:
      - htop
      - tmux
      - python3-psutil
      - neovim
      - dconf
      - tshark
      - wireshark-qt
      - macchanger
      - binwalk
      - npm
      - gcc
      - ripgrep
      - fail2ban
      - firewalld
      - firewalld-filesystem
      - gcc-c++
      - gdb-doc
      - gnome-shell-extension-gpaste
      - gnome-tweak-tool
      - golang
      - golang-godoc
      - golang-gotype
      - gotags
      - gpaste
      - letsencrypt
      - lftp
      - libguestfs
      - libguestfs-tools
      - libguestfs-tools-c
      - libguestfs-xfs
      - libicns-utils
      - libmtp-examples
      - libnfs
      - libnfsidmap
      - libsemanage-devel
      - libtaskotron  # Verify this package availability
      - libtool
      - libvirt
      - libvirt-sandbox
      - livecd-tools
      - liveusb-creator
      - lm_sensors
      - nmap
      - nmon
      - nodejs
      - psad
      - pssh
      - pv
      - pykickstart
      - pylint
      - pyp2rpm
      - pypy
      - pytest
      - python3-firewall
      - python3-virtualenv
      - sysstat
      - system-storage-manager
      - task
      - tcllib
      - terminator
      - testcloud
      - testdisk
      - transmission-cli
      - tuna
      - tuned
      - tuned-utils
      - tuned-utils-systemtap
      - units
      - vagrant
      - vagrant-doc
      - valgrind
      - vim-enhanced
      - virt-top
      - whois
      - wireshark-cli
      - xbacklight
      - xclip
      - xfsdump
      - xournal
      - xseli
      - python3-pip
    state: installed
    update_cache: yes
  ignore_errors: yes






- name: Package debug 2 
  debug:
    msg: "After all packages"

#- name: Install Python Libraries
 # become: true
 # dnf:
  #  name:

 # ignore_errors: yes