--- 
- name: Package debug 
  debug:
    msg: "Updgrading all packages"
- name: Upgrade all packages
  dnf: 
    name: "*"
    state: latest

#- name: Install group packages whenever I make groups :)
## dnf: 
#    name:
#       - "@TacoBell"
#    state: installed



- name: Display the value of ansible_distribution
  debug:
    msg: "Installing all packages"

- name: Install development tools
  become: true
  dnf:
    name:
      - gcc
      - gcc-c++
      - gdb-doc
      - golang
      - golang-godoc
      - golang-gotype
      - gotags
      - nodejs
      - npm
      - python3-pip
      - pykickstart
      - pylint
      - pyp2rpm
      - pypy
      - pytest
      - psutil
      - python3-psutil
    state: installed
    update_cache: yes
  ignore_errors: yes

- name: Install system tools
  become: true
  dnf:
    name:
      - dconf
      - gnome-tweaks
      - htop
      - tmux
      - neovim
      - dconf
      - firewalld
      - firewalld-filesystem
      - lm_sensors
      - sysstat
      - system-storage-manager
      - tuned
      - tuned-utils
      - tuned-utils-systemtap
    state: installed
    update_cache: yes
  ignore_errors: yes

- name: Install network tools
  become: true
  dnf:
    name:
      - tshark
      - wireshark-qt
      - macchanger
      - binwalk
      - nmap
      - nmon
      - psad
      - pssh
    state: installed
    update_cache: yes
  ignore_errors: yes










- name: Package debug 2 
  debug:
    msg: "After all packages"




- name: Check for psutil Python module
  command: python3 -c "import psutil"
  register: psutil_check
  ignore_errors: true

- name: Output result of psutil check
  debug:
    msg: "psutil is installed."
  when: psutil_check.rc == 0

- name: Output result of psutil check
  debug:
    msg: "psutil is not installed."
  when: psutil_check.rc != 0