---
- name: Gather list of user home directories
  command: ls /home/
  register: users

- name: Remove existing Neovim configuration files for each user
  file:
    path: "/home/{{ item }}/config/nvim"
    state: absent
  loop: "{{ users.stdout_lines }}"

- name: Create Neovim configuration directory for each user
  file:
    path: "/home/{{ item }}/.config/nvim"
    state: directory
    mode: '0755'
  loop: "{{ users.stdout_lines }}"

- name: Add initial Neovim configuration for each user
  copy:
    content: |
      set number
      syntax on
      filetype plugin indent on
    dest: "/home/{{ item }}/.config/nvim/init.vim"
  loop: "{{ users.stdout_lines }}"

- name: Install vim-plug for plugin management for each user
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{ item }}/.