---
- name: Setup Workstation
  hosts: localhost  # This line was missing in your provided examples; ensure you define which hosts to target.
  gather_facts: true  # This can be set to true or false depending on whether you need to gather facts.

  vars_files:
    - Fedora-workstation/vars/vars.yml

  tasks:
    - name: Include Fedora repos setup
      include_tasks: Fedora-workstation/tasks/fedorarepos.yml

    - name: Include package setup
      include_tasks: Fedora-workstation/tasks/packages.yml

    - name: Include user setup
      include_tasks: Fedora-workstation/tasks/users.yml

    - name: Include service setup
      include_tasks: Fedora-workstation/tasks/services.yml

    - name: Include system setup
      include_tasks: Fedora-workstation/tasks/system.yml

    - name: Include third-party software setup
      include_tasks: Fedora-workstation/tasks/thirdparty.yml

    - name: Include system hardening setup
      include_tasks: Fedora-workstation/tasks/harden.yml

  handlers:
    - name: Import main handlers
      import_tasks: Fedora-workstation/handlers/main.yml
