---
- hosts: workstation
  become: true
  gather_facts: true

  vars_files:
    - Fedora-workstation/vars/main.yml

- import_playbook: Fedora-workstation/playbooks/Fedora-repos.yml
- import_playbook: Fedora-workstation/playbooks/Packages.yml
- import_playbook: Fedora-workstation/playbooks/Users.yml
- import_playbook: Fedora-workstation/playbooks/Services.yml
- import_playbook: Fedora-workstation/playbooks/System.yml
- import_playbook: Fedora-workstation/playbooks/Thirdparty.yml
- import_playbook: Fedora-workstation/playbooks/Harden.yml

# Handlers are typically used within playbooks so you might need to reorganize
# how these are imported or triggered.

 # handlers:
  ##   import_tasks: handlers/main.yml
