---
- name: Setup Workstation
  hosts: workstation
  become: true
  gather_facts: true

  vars_files:
    - vars/vars.yml

  tasks:
    - name: Include repositories setup tasks
      include_tasks: Fedora-workstation/tasks/fedorarepos.yml

    - name: Include packages installation tasks
      include_tasks: Fedora-workstation/tasks/packages.yml

    - name: Include users management tasks
      include_tasks: Fedora-workstation/tasks/users.yml

    - name: Include services setup tasks
      include_tasks: Fedora-workstation/tasks/services.yml

    - name: Include system setup tasks
      include_tasks: Fedora-workstation/tasks/system.yml

    - name: Include third-party software installation tasks
      include_tasks: Fedora-workstation/tasks/thirdparty.yml

    - name: Include system hardening tasks
      include_tasks: Fedora-workstation/tasks/harden.yml

  handlers:
    - name: Import main handlers
      import_tasks: Fedora-workstation/handlers/main.yml
