---
- name: Setup Workstation
  hosts: localhost  # Ensuring 'hosts' directive is present and correctly indented
  gather_facts: true  # Ensure 'gather_facts' is correctly indented and set

  vars_files:
    - Fedora-workstation/vars/vars.yml  # Check that the path is correct and file exists

  tasks:
    - name: Include Fedora repos setup
      include_tasks: Fedora-workstation/tasks/fedorarepos.yml

    - name: Include package setup
      include_tasks: Fedora-workstation/tasks/packages.yml

    - name: Include user setup
      include_tasks: Fedora-workstation/tasks/users.yml

    - name: Include service setup
      include_tasks: Fedora-workstation/tasks/services.yml

    - name: Include system setup
      include_tasks: Fedora-workstation/tasks/system.yml

    - name: Include third-party software setup
      include_tasks: Fedora-workstation/tasks/thirdparty.yml

    - name: Include system hardening setup
      include_tasks: Fedora-workstation/tasks/harden.yml

  handlers:
    - name: Import main handlers
      import_tasks: Fedora-workstation/handlers/main.yml
