---
- name: Setup Workstation
  hosts: localhost
  gather_facts: true
  vars_files:
    - Fedora-workstation/vars/vars.yml

  tasks:
    - name: Import tasks
      include_tasks: Fedora-workstation/tasks/fedorarepos.yml
    - include_tasks: Fedora-workstation/tasks/packages.yml
    - include_tasks: Fedora-workstation/tasks/users.yml
    - include_tasks: Fedora-workstation/tasks/services.yml
    - include_tasks: Fedora-workstation/tasks/system.yml
    - include_tasks: Fedora-workstation/tasks/thirdparty.yml
    - include_tasks: Fedora-workstation/tasks/harden.yml

  handlers:
    - name: Import handlers
      import_tasks: Fedora-workstation/handlers/main.yml
