---
- name: Setup Workstation
  hosts: workstation

  vars_files:
    - Fedora-workstation/vars/vars.yml

  tasks:
    - include_tasks: Fedora-workstation/tasks/fedorarepos.yml
    - include_tasks: Fedora-workstation/tasks/packages.yml
    - include_tasks: Fedora-workstation/tasks/users.yml
    - include_tasks: Fedora-workstation/tasks/services.yml
    - include_tasks: Fedora-workstation/tasks/system.yml
    - include_tasks: Fedora-workstation/tasks/thirdparty.yml
    - include_tasks: Fedora-workstation/tasks/harden.yml

  handlers:
    - import_tasks: Fedora-workstation/handlers/main.yml